package com.booklist.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.List;

/**
 * Entity mapped to table "BOOK".
 */
public class Book {

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String pubdate;
    /** Not-null value. */
    private String publisher;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String summary;

    private String catalog;

    private String author_intro;

    private Rating rating;

    private List<String> author;

    private List<Tag> tags;
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Book() {
    }

    public Book(String id, String title, String pubdate, String publisher, String image, String summary) {
        this.id = id;
        this.title = title;
        this.pubdate = pubdate;
        this.publisher = publisher;
        this.image = image;
        this.summary = summary;
    }

    public Rating getRating() {
        return rating;
    }

    public String getCatalog() {
        return catalog;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    public String getAuthor_intro() {
        return author_intro;
    }

    public void setAuthor_intro(String author_intro) {
        this.author_intro = author_intro;
    }

    public void setRating(Rating rating) {
        this.rating = rating;
    }

    public List<String> getAuthor() {
        return author;
    }

    public void setAuthor(List<String> author) {
        this.author = author;
    }

    public List<Tag> getTags() {
        return tags;
    }

    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getPubdate() {
        return pubdate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPubdate(String pubdate) {
        this.pubdate = pubdate;
    }

    /** Not-null value. */
    public String getPublisher() {
        return publisher;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getSummary() {
        return summary;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
